Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Exclude:
    - lib/imaterialise/version.rb
    - spec/**/*

Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma

Style/BlockDelimiters:
  Enabled: false
